### ISSUE TITLE
useForFieldJob="true" on new HE fruits

### ISSUE THREAD

**Issue by MBTrac366** [Tresk7924/HorseExtension#12]
I just noticed, the attribute useForFieldJob is set to true on almost all new HE fruits (alfalfa, clover, fieldgrass etc). As far as I know, this can cause some issues and this attribute should be set to false by default.

**Comment by sashaman** [comment]
ifko granted me permission to include fieldmanagerfix. 
grab a copy of my 🍴 fork or wait for tresk to update/merge

**Comment by sashaman** [comment]
i "corrected" those entries
