### ISSUE TITLE
fruittype limit conversion and 16 fruittype slots

### ISSUE THREAD

**Issue by sashaman** [Tresk7924/HorseExtension#4]
so basically, if the map that is going to be converted has max. 16 fruits in the maps i3d FoliageMultiLayer, the conversion is flawless and no further intervention is required. 
BUT if the map is already using 17 or more fruits, it needs to be converted because starting with the 17th entry indices start to get out of order when converted (the Nth entry isnt being pixel shifted to the correct rgb channels). 

the tutorial containing the python code snippets as well as an updated all-in-1 solution .exe are available [here](https://ls-modcompany.com/forum/thread/8049-limit-f%C3%BCr-fruchtsorten-in-beliebiger-map-erh%C3%B6hen/?postID=93808#post93808)

this is important info, but i feel incorporating how to do that as well is out of scope of this tutorial / package. 

what are your thoughts ?

**Comment by Tresk7924** [comment]
Yeah, I want to include something about this. I've done map conversions that have changed all the grass into potatoes, for instance, and the solution I bodged together was to edit the fruit_density.png in GIMP, but obviously properly dealing with the issue would be better.

I'll try to incorporate this in the next version.

**Comment by sashaman** [comment]
i removed fruit_density conversion from readme.md and added a note/hint with link to FruitDensityManager. 
including that step is simply not necessary and by no means fit in this tutorial. 
whoever really wants/needs help will find his way to m+ discord where i will gladly help and instruct

**Comment by Tresk7924** [comment]
Resolved with fruit_density.png converter in 856826fca6ad609ac47b98dd0bf60b4ed8e8bf40
