### ISSUE TITLE
Silo/Hayloft ADDITIONS AND fillType vs. fillTypeCategory

### ISSUE THREAD

**Issue by sashaman** [Tresk7924/HorseExtension#5]
### regarding readme and the Silo/Hayloft ADDITIONS:

to be able to flawlessly use the **fillTypeCategories FARMSILO and HAYLOFT** , 
i.e.
```
    <storages>
        <storage node="3|0" fillTypeCategories="hayloft" capacityPerFillType="250000" />
    </storages>
```
consistent and working standard entries are required. 

the current state doesn't seem to make too much sense, f.e. MISCANTHUS prolly better fits inside HAYLOFTS rather than silos, 
as well as the (additional) drying stages of m+ weeds. 
then what about the fermented stuff, does it better fit haylofts or silos?

default setting:
```xml
<fillTypeCategory name="FARMSILO" >WHEAT BARLEY OAT CANOLA SUNFLOWER SOYBEAN MAIZE POTATO SUGARBEET SUGARCANE</fillTypeCategory>

<fillTypeCategory name="HAYLOFT" >STRAW DRYGRASS_WINDROW</fillTypeCategory>
```

M+HE entries:
```xml
<fillTypeCategory name="FARMSILO"	>SPELT RYE TRITICALE MISCANTHUS CLOVER WETCLOVER_WINDROW CLOVER_WINDROW DRYCLOVER_WINDROW WETALFALFA_WINDROW ALFALFA_WINDROW ALFALFA_FERMENTED CLOVER_FERMENTED FIELD_GRASS ONION CARROT WHEAT BARLEY OAT CANOLA SUNFLOWER SOYBEAN MAIZE POTATO SUGARBEET</fillTypeCategory>

<fillTypeCategory name="HAYLOFT"	>DRYHORSEGRASS_WINDROW STRAW DRYGRASS_WINDROW DRYALFALFA_WINDROW DRYCLOVER_WINDROW</fillTypeCategory>
```

proposal: 
```xml
<fillTypeCategory name="FARMSILO" >WHEAT BARLEY OAT CANOLA SPELT RYE TRITICALE SUNFLOWER SOYBEAN MAIZE FIELD_GRASS POTATO SUGARBEET ONION CARROT SUGARCANE</fillTypeCategory>

<fillTypeCategory name="HAYLOFT"	>STRAW DRYGRASS_WINDROW DRYHORSEGRASS_WINDROW ALFALFA WETALFALFA_WINDROW ALFALFA_WINDROW SEMIDRYALFALFA SEMIDRYALFALFA_WINDROW DRYALFALFA_WINDROW ALFALFA_FERMENTED CLOVER WETCLOVER_WINDROW CLOVER_WINDROW SEMIDRYCLOVER SEMIDRYCLOVER_WINDROW DRYCLOVER_WINDROW CLOVER_FERMENTED MISCANTHUS</fillTypeCategory>
```
what are your thoughts, what makes sense and what's unnecessary? 
maybe interview Paul? xd 

regards

**Comment by Tresk7924** [comment]
Sorry, completely missed this. The "farmsilo" is a bit weird, since Giants don't really use it either.

I'm going to go with a restrictive definition in line with what you can actually store in the default silos, giving
`<fillTypeCategory name="FARMSILO" 		>SPELT RYE TRITICALE MISCANTHUS FIELD_GRASS WHEAT BARLEY OAT CANOLA SUNFLOWER SOYBEAN MAIZE</fillTypeCategory>`

Potato, sugarbeet, onion, carrot, and sugarcane shouldn't be in there, just based on what they'd do to a grain auger, and what that auger would do to them. I'll add something to the tutorial for those who want to edit their silos.

**Comment by sashaman** [comment]
miscanthus isnt crop here, its more like chaff or straw, thats why its imho totally wrong in silos
also iirc Paul said that its not gonna stay, afaik it should be gone/replaced in terralife

the FS default file has 
`        <fillTypeCategory name="FARMSILO" >WHEAT BARLEY OAT CANOLA SUNFLOWER SOYBEAN MAIZE POTATO SUGARBEET SUGARCANE</fillTypeCategory>`
so u see sugarcane is already there and (same with cotton?) seemingly was edited out by FA (the intention was to completely remove and disable cotton + sugarcane)

**Comment by sashaman** [comment]
p.s. the farmsilo category seems to be in use in a single placeable - a silo at a trainstation lol 
maybe some1 forgot to put it to proper use haha

**Comment by sashaman** [comment]
the original game file entry is
```
<fillTypeCategory name="FARMSILO" >WHEAT BARLEY OAT CANOLA SUNFLOWER SOYBEAN MAIZE POTATO SUGARBEET SUGARCANE</fillTypeCategory>
```
the fact that the **farmsilo category is used in a trainstation silo on base map AS WELL AS the base game SILO EXTENSION placeable** implies the requirement to add back in the standards POTATO SUGARBEET SUGARCANE (also because they are in this category in the game default filltypes.xml), _else these wont work with said placeable anymore_

```
<fillTypeCategory name="FARMSILO" >WHEAT BARLEY OAT CANOLA SUNFLOWER SOYBEAN MAIZE POTATO SUGARBEET SUGARCANE FIELD_GRASS RYE SPELT TRITICALE</fillTypeCategory>
```
